import Link from "next/link";
import { Alert } from "@/components/ui/Alert";
import { Card } from "@/components/ui/Card";
import { getSchoolUsageSnapshot } from "@/lib/billing/usageSnapshot";
import { formatPlatformPrice } from "@/lib/billing/access";
import { CapacityControls } from "@/app/admin/facturacion/CapacityControls";
const hours = (value: unknown) => (Number(value)/3600).toLocaleString("es-ES",{maximumFractionDigits:2});
const minutes = (value: unknown) => (Number(value)/60).toLocaleString("es-ES",{maximumFractionDigits:1});
const date = (value: string) => new Date(value).toLocaleString("es-ES",{timeZone:"Europe/Madrid"});
export async function SchoolUsagePanel({ organizationId, controls = false }: { organizationId: string; controls?: boolean }) {
  const s=await getSchoolUsageSnapshot(organizationId);
  if (s.kind === "error") return <Alert variant="info">{s.message}</Alert>;
  const b=s.billing, c=s.cycle;
  const active=Number(s.library.active_seconds), reserved=Number(s.library.reserved_seconds), committed=Number(s.library.committed_seconds);
  const planName=b.accepted_offer?.name ?? "Oferta anterior";
  const invoice=s.invoices.find(i=>i.currency==="eur");
  return <section className="space-y-6" aria-label="Consumo y capacidad">
    <div><h2 className="text-xl font-semibold">Consumo y capacidad · {planName}</h2><p className="mt-2 text-sm text-muted-foreground">{b.offer_version ? `Oferta ${b.offer_version}. ${b.quota_mode === "enforce" ? "Control de capacidad activo." : "Medición en observación."}` : "Tu contrato anterior conserva sus condiciones; sin activar cuotas ni conservación de forma retroactiva."}</p></div>
    <div className="grid gap-4 md:grid-cols-2"><Card className="space-y-3 p-5"><h3 className="font-semibold">Biblioteca</h3><p>{hours(active)} h alojadas · {hours(reserved)} h reservadas {b.offer_version ? `de ${hours(b.library_limit_seconds)} h` : ""}</p><p className="text-sm text-muted-foreground">Capacidad pendiente de liberar: {hours(committed)} h.{s.library.release_at ? ` Próxima liberación prevista: ${date(s.library.release_at)}.` : ""} Al sustituir un vídeo se reserva también el nuevo hasta validarlo.</p>{Number(s.library.unconfirmed_assets)>0 ? <Alert variant="info">Hay duraciones pendientes de confirmar con el proveedor.</Alert> : null}{b.library_excess_since ? <Alert variant="info">Biblioteca por encima del techo. Nuevas subidas bloqueadas; plazo de ajuste hasta {date(new Date(Date.parse(b.library_excess_since)+7*86400000).toISOString())}. Después se pausan nuevas reproducciones mientras continúe el exceso.</Alert> : null}<p className="text-sm">Ampliaciones recurrentes: {b.library_extension_quantity} × 10 h · {formatPlatformPrice(b.library_extension_quantity*800)}/mes.</p></Card>
      <Card className="space-y-3 p-5"><h3 className="font-semibold">Reproducción compartida</h3>{c ? <><p>Ciclo: {date(c.starts_at)} – {date(c.ends_at)}</p><p>Confirmada: {s.confirmedKnown ? `${minutes(s.confirmedSeconds)} min` : "pendiente de datos fiables"}.</p><p>Base: {s.confirmedKnown ? minutes(c.base_used_seconds) : "pendiente"} / {minutes(c.base_seconds)} min. Gracia: {s.confirmedKnown ? minutes(c.grace_used_seconds) : "pendiente"} / {minutes(c.grace_seconds)} min.</p></> : <p className="text-muted-foreground">Ciclo pendiente de conciliación.</p>}<p className="text-sm text-muted-foreground">Estimación reciente: {s.estimatedSeconds === null ? "pendiente de telemetría" : `${minutes(s.estimatedSeconds)} min aproximados`}; se muestra separada del uso confirmado. {s.updatedAt ? `Última actualización fiable: ${date(s.updatedAt)}.` : "Todavía no hay actualización fiable."}</p>{s.pending ? <Alert variant="info">Actualización pendiente. La falta de datos no significa consumo cero.</Alert> : null}</Card></div>
    <Card className="space-y-3 p-5"><h3 className="font-semibold">Bolsas de reproducción</h3>{s.packs.length ? <ul className="space-y-3">{s.packs.map(p=><li key={p.id} className="flex flex-col justify-between gap-1 text-sm sm:flex-row"><span>{minutes(p.remaining_seconds)} minutos restantes</span><span>{p.expired ? "Vencida" : "Vence"}: {date(p.expires_at)}</span></li>)}</ul> : <p className="text-sm text-muted-foreground">No hay bolsas. Son pagos únicos y no se renuevan automáticamente.</p>}</Card>
    <p className="text-sm text-muted-foreground">Última factura registrada: {invoice ? `${formatPlatformPrice(invoice.amount_paid_cents)} pagados el ${date(invoice.paid_at)}` : "importe real pendiente de conciliación"}. El precio, descuentos y facturas de Stripe prevalecen para tus cobros.</p>
    {s.operations.length ? <Alert variant="info">{s.operations.map(op=>`${op.kind}: ${op.status}${op.last_error ? " (requiere conciliación)" : ""}`).join(" · ")}</Alert> : null}
    {b.retention_until ? <Alert variant="info">Conservamos tu contenido hasta {date(b.retention_until)}. Puedes recuperar la suscripción o <Link href={`/api/admin/content-export?organizationId=${organizationId}`} className="underline">extraer tus datos y contenido disponible</Link>. Las facturas se conservan por separado.</Alert> : null}
    {controls ? <CapacityControls organizationId={organizationId} planKey={b.plan_key} libraryQuantity={b.library_extension_quantity} subscriptionActive={Boolean(b.platform_subscription_id && ["active","past_due"].includes(b.platform_subscription_status))} enabled={process.env.PLATFORM_PLANS_ENABLED==="true"} /> : null}
  </section>;
}
